name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Python and pip versions
        run: |
          python --version
          pip --version

      - name: Run Hello Unicorns
        run: python hello_unicorns.py

      - name: Run Thunkable Link Checker
        run: python check_thunkable_links.py